### ISSUE TITLE
TestNet

### ISSUE THREAD

**Issue by roughpandaz** [mtlynch/ansible-role-sia#33]
Hi Michael,

Quick question.

Do you know of any solution to this problem?
https://github.com/NebulousLabs/Sia-Ant-Farm/issues/77

What is your suggestion for running a testnet with Sia such that I don't need to pay and purchase with real tokens?

Thanks!

**Comment by mtlynch** [comment]
I'd wondered about that myself, but I've never invested the time into figuring out. It's definitely possible to do, but it's a question of how much fiddling you'll have to do with the Sia code.

**Comment by roughpandaz** [comment]
@mtlynch Got it, thank you!
